# Header

menu:
  主页: /
  HTML: /tags/HTML/
  CSS: /tags/CSS

# SubNav
subnav:
  github: https://github.com/Guanruiting
  weibo: https://weibo.com/1909056972
  #rss: "#"
  zhihu: https://www.zhihu.com/people/guan-rui-ting/pins
  qq: https://user.qzone.qq.com/188005910/main
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我喝可乐'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.png
# 微信二维码图片地址
weixin: /img/wechat.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/sunflower.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#000e31'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '链接'
  aboutme: '关于我'

friends:
  百度搜索: http://www.baidu.com/
  Hexo: https://hexo.io/zh-cn/docs/
  Markdown语法: https://www.appinn.com/markdown/
  Javascript在线教程: https://wangdoc.com/javascript/
  在线作图: https://www.processon.com/
  segmentfault: https://segmentfault.com/
  segmentfault前端: https://segmentfault.com/channel/frontend
  印记中文: https://docschina.org/
  菜鸟教程: http://www.runoob.com/
  千图网: https://www.58pic.com/
  有道云笔记: https://note.youdao.com
  网易云课堂: https://study.163.com/
  前端大牛（张鑫旭）: https://www.zhangxinxu.com/
  凹凸实验室: https://aotu.io/
  在线代码格式化: http://tool.oschina.net/codeformat/json




aboutme: 一个小前端<br>2019年开始接触互联网，<br>可惜至今一无所成，除了有一份还不错的工作。<br>大学原来学日语专业的，<br>但目前日语仅用于自娱自乐，听歌看动漫。<br>85后女汉子<br>两个小孩的妈妈啦！<br>座右铭：吃得苦中苦，方为人上人。